registry:
  restart: always
  image: registry
#  ports:
#    - "5000:5000"
  environment:
    STORAGE_PATH: "/var/lib/registry"
    SEARCH_BACKEND: "sqlalchemy"
  volumes:
    - "/var/lib/registry:/var/lib/registry"
    #- "/home/dan/docker/volumes/registry:/var/lib/registry"

ui:
  restart: always
  image: konradkleine/docker-registry-frontend
  # ports:
  #   - "7080:80"
  links:
    - "registry:registry"
  environment:
    ENV_DOCKER_REGISTRY_HOST: registry
    ENV_DOCKER_REGISTRY_PORT: 5000

nginx:
  restart: always
  build: nginx/
  volumes:
    - "./nginx/configs/certs/:/etc/nginx/certs"
  links:
    - "registry:registry"
    - "ui:ui"
  ports:
    - "5000:5000"
    - "8080:8080"
    - "8081:8081"
    - "7081:7081"
    - "80:80"