production:
  adapter: mysql2
  database: openproject
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  username: openproject
  password: openproject
  encoding: utf8
development:
  adapter: mysql2
  database: openproject_development
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  username: openproject
  password: openproject
  encoding: utf8
test:
  adapter: mysql2
  database: openproject_test
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  username: openproject
  password: openproject
  encoding: utf8
